export const featured = [
  {
    id: 1,
    img: "/images/Nest-Tables.jpg",
    cat: "Nest Of Tables",
    title: "Caroline Study Tables",
    cutPrice: "Rs. 3,000",
    price: " Rs. 2,500",
  },
  {
    id: 2,
    img: "/images/Coffee-Table.jpg",
    cat: "Coffee Tables",
    title: "Evan Coffee Table",
    cutPrice: "Rs. 2,600",
    price: " Rs. 2,300",
  },
  {
    id: 3,
    img: "/images/Shoe-Racks.jpg",
    cat: "Shoe Racks",
    title: "Gloria Shoe Racks",
    cutPrice: "Rs. 3,400",
    price: "Rs. 2,900",
  },
  {
    id: 4,
    img: "/images/Bookshelfs-brown.jpg",
    cat: "Bookshelves",
    title: "Erica Bookshelfs",
    cutPrice: "Rs. 38,000",
    price: "Rs. 30,000",
  },
  {
    id: 5,
    img: "/images/Sofa-Cum-Bed.jpg",
    cat: "Wooden Sofa Cum Bed",
    title: "Sapien Sofa Cum Bed",
    cutPrice: "Rs. 64,000",
    price: "Rs. 54,000",
  },
  {
    id: 6,
    img: "/images/Sofa-Set.jpg",
    cat: "2 Seater Sofa",
    title: "Ganthur Sheesham Wood Sofa Set",
    cutPrice: "Rs. 8,000",
    price: "Rs. 7,600",
  },
  {
    id: 7,
    img: "/images/Swing-Jhula.jpg",
    cat: "Wooden Jhula",
    title: "Calina Swing Jhula",
    cutPrice: "Rs. 65,000",
    price: "Rs. 58,000",
  },
];

export const newArrivals = [
  {
    id: 1,
    img: "/images/Stool.jpg",
    cat: "Side and End Tables",
    title: "Hrithvik Stool",
    cutPrice: "Rs. 7,000",
    price: "Rs. 6,000",
  },
  {
    id: 2,
    img: "/images/Coffee-Table-Set.jpg",
    cat: "Coffee Table Sets",
    title: "Godfrey Coffee Table Set",
    cutPrice: "Rs. 3,000",
    price: "Rs. 2,200",
  },
  {
    id: 3,
    img: "/images/Shoe-Rack_.jpg",
    cat: "Display Unit",
    title: "Dorian Shoe Rack",
    cutPrice: "Rs. 3,500",
    price: "Rs. 2,800",
  },
  {
    id: 4,
    img: "/images/Cabinet.jpg",
    cat: "Cabinets and Sideboard",
    title: "Louise Cabinet",
    cutPrice: "Rs. 28,000",
    price: "Rs. 23,000",
  },
  {
    id: 5,
    img: "/images/Mirror.jpg",
    cat: "Wooden Mirrors",
    title: "Winona Mirror",
    cutPrice: "Rs. 2,000",
    price: "Rs. 1,500",
  },
  {
    id: 6,
    img: "/images/Group-1.jpg",
    cat: "1 Seater Sofa",
    title: "Yuvi sheesham wood sofa set",
    cutPrice: "Rs. 10,000",
    price: "Rs. 7,600",
  },
  {
    id: 7,
    img: "/images/Group-2.jpg",
    cat: "Wooden Sofa Sets",
    title: "Grace Sheesham Wood Sofa Set",
    cutPrice: "Rs. 90,000",
    price: "Rs. 72,000",
  },
];

export const onSale = [
  {
    id: 1,
    img: "/images/Console-Table.jpg",
    cat: "Console Table",
    title: "Rex Console Table",
    cutPrice: "Rs. 3,000",
    price: "Rs. 2,200",
  },
  {
    id: 2,
    img: "/images/Temple-Prayer-Unit.jpg",
    cat: "Prayer Units",
    title: "Hardwell Temple Prayer Unit",
    cutPrice: "Rs. 10,000",
    price: "Rs. 9,400",
  },
  {
    id: 3,
    img: "/images/Chest-of-Drawer.jpg",
    cat: "Chest Of Drawers",
    title: "Isaac Chest of Drawer",
    cutPrice: "Rs. 32,000",
    price: "Rs. 25,000",
  },
  {
    id: 4,
    img: "/images/TV-Cabinets.jpg",
    cat: "Tv Units",
    title: "Leo TV Cabinets",
    cutPrice: "Rs. 26,000",
    price: "Rs. 21,000",
  },
  {
    id: 5,
    img: "/images/Group-3.jpg",
    cat: "L Shape Sofa",
    title: "Harper L Shaped Wooden Sofa with Drawer",
    cutPrice: "Rs. 85,000",
    price: "Rs. 76,000",
  },
  {
    id: 6,
    img: "/images/Group-4.jpg",
    cat: "3 Seater Sofa",
    title: "Victoria Sheesham Wood Sofa Set",
    cutPrice: "Rs. 8,000",
    price: "Rs. 7,000",
  },
];
